name: "NixVim Config Check"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check Flake
        run: nix flake check
